### ISSUE TITLE
A card's text is covered

### ISSUE THREAD

**Issue by fire** [AcademySoftwareFoundation/aswf-landscape#51]
![image](https://user-images.githubusercontent.com/32321/78193263-fa9afb80-742e-11ea-8bfa-592ce82e02b1.png)

Not sure how to solve by pull request.

**Comment by jmertic** [comment]
I'm not seeing this in the latest build - can you verify? Or let me know which browser you are using if you do see it?

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/82939521-52924200-9f48-11ea-9134-d0029991c18e.png)

On Firefox.

"The landscape is rendered.." Section overflows its box.

**Comment by fire** [comment]
Seems to work on https://landscape.aswf.io/
![image](https://user-images.githubusercontent.com/32321/82940891-4dce8d80-9f4a-11ea-9694-0663f04f9fa2.png)

**Comment by fire** [comment]
Fails on https://landscape.aswf.io/images/landscape.png and https://landscape.aswf.io/images/landscape.pdf.

**Comment by fire** [comment]
Problem: You may want a poster of this at some point.

**Comment by jmertic** [comment]
Thanks - was able to reproduce on Chrome as well.

Take a look now and see if it looks better.

**Comment by fire** [comment]
It's slightly better. https://landscape.aswf.io/images/landscape.png

![image](https://user-images.githubusercontent.com/32321/82942904-920f5d00-9f4d-11ea-9c70-0544b70d4822.png) (Screenshot in browser)

There's large gaps between the words for "The Academy Software Foundation."

**Comment by jmertic** [comment]
Try now - it looks like we have that synced up now.
