### ISSUE TITLE
New Landscape Entry - Appleseed

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/aswf-landscape#717]
### Project Name

Appleseed

### Description

appleseed is an open source, physically-based global illumination rendering engine primarily designed for animation and visual effects. It provides individuals and small studios with a complete, reliable, fully open rendering package built with modern technologies.

### Homepage URL

https://appleseedhq.net/

### Repo URL

https://github.com/appleseedhq

### Organization hosting or owning the project

dunno

### Logo

https://appleseedhq.net/img/appleseed-website-logo.png

### Category

Rendering and Queueing - Rendering, Lighting, and Lookdev

**Comment by jmertic** [comment]
Hey @dictoon! Would like to get appleseed added to the ASWF Landscape - would you have a clean SVG of the logo we could use? Thanks in advance!

**Comment by dictoon** [comment]
Hi @jmertic, you can find all logos in SVG and high resolution PNG forms in the GitHub repo, here:
https://github.com/appleseedhq/appleseed/tree/master/resources/logo

**Comment by jmertic** [comment]
Great, thanks! Take a look at the entry and let me know if it's accurate.

https://deploy-preview-718--awsf-landscape.netlify.app/?selected=appleseed

**Comment by dictoon** [comment]
Looks good, thanks!

**Comment by jmertic** [comment]
Great - thanks!
