### ISSUE TITLE
New Landscape Entry - StratusGFX

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/aswf-landscape#731]
### Project Name

StratusGFX

### Description

StratusGFX is a realtime 3D rendering engine.

### Homepage URL

https://ktstephano.github.io/portfolio

### Repo URL

https://github.com/KTStephano/StratusGFX

### Organization hosting or owning the project

KTStephano

### Logo

TODO

### Category

Rendering and Queueing - Rendering, Lighting, and Lookdev

**Comment by KTStephano** [comment]
@jmertic Sounds good, I'll keep you posted if any big projects pick it up! Let me get back to you on the logo.

**Comment by jmertic** [comment]
Hey @KTStephano - any updates here?

**Comment by KTStephano** [comment]
No updates from me yet, development is still going on but no production usage.

**Comment by jmertic** [comment]
Thanks for the update!

**Comment by jmertic** [comment]
Hi @KTStephano - looks like you have a logo created...

https://user-images.githubusercontent.com/8399235/254135954-84b9cb9a-b01e-43e0-8a3c-16217af4432e.jpg

Any chance you'd have an SVG, AI, or similar vector version?

**Comment by KTStephano** [comment]
Hi @jmertic , yeah let me link an svg with and without background. Other than that no new updates but development is ongoing.

![StratusGFX_Logo](https://github.com/AcademySoftwareFoundation/aswf-landscape/assets/8399235/ce531abe-a3f7-4298-8107-99c04eaacc81)

![StratusGFX_Logo_Transparent](https://github.com/AcademySoftwareFoundation/aswf-landscape/assets/8399235/4a41bdea-0d1a-421c-bf6a-84d33a9e7b58)
