### ISSUE TITLE
Update Landscape Entry for PySceneDetect

### ISSUE THREAD

**Issue by Breakthrough** [AcademySoftwareFoundation/aswf-landscape#779]
### Changes requested

Hello;

The license for the project [PySceneDetect](github.com/Breakthrough/PySceneDetect) is BSD 3-Clause.

Thanks!

P.S. I appreciate your work and glad you all find the project useful :)

**Comment by jmertic** [comment]
Hi @Breakthrough, thanks for the kind words and for reaching out.

One thing to note is that the Landscape pulls what GitHub says the license is; you can read more about it at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license and see the actual project used at https://github.com/licensee/licensee.

Looking at your LICENSE file ( https://github.com/Breakthrough/PySceneDetect/blob/main/LICENSE ), it appears you put both the primary license and the licenses for third-party components in that file. If you'd separate those third-party licenses into a separate file ( such as THIRD-PARTY.md ), that should fix the license detection. Check out how OpenColorIO does this ( https://github.com/AcademySoftwareFoundation/opencolorio ) for an example pattern to follow.

Hopefully this helps!

**Comment by Breakthrough** [comment]
Thanks so much for the suggestion, I'll be sure to update that for the next release of PySceneDetect.  Appreciate the reply!
